name: CI
on:
  pull_request_target:
    types:
      - closed

jobs:
  update_dependency:
    env:
      ACCESS_TOKEN: "access_token"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: A job to update dependency
    steps:
      - name: step
        uses: IamAbbey/test-docker-action