name: CI
on:
  pull_request_target:
    types:
      - closed

jobs:
  update_dependency:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: A job to update dependency
    steps:
      - name: step
        uses: IamAbbey/test-docker-action@main
        with:
          destination_repo: 'test-dep-ci-v2'
          dependency_name: 'test-dep-ci-v1'
          access_token: ${{ secrets.API_TOKEN_GITHUB }}
          ssh_key: ${{ secrets.SSH_KEY }}